### ISSUE TITLE
Functions/lambdas

### ISSUE THREAD

**Issue by nanalan** [nanalan/wew#2]
At the moment I'm liking this es6-inspired syntax:

```wew
# anonymous function
noun => "Nice " .. noun .. "!"

# named function + type guard
nice(noun: String) => "Nice " .. noun .. "!"
```

~~Function return type can probably be inferred by the programmer.~~

**Comment by BookOwl** [comment]
If you are going to have types, you should probably annotate the return type too.
My two 💵

**Comment by nanalan** [comment]
@BookOwl I agree. Not sure about the syntax for it though.

**Comment by nanalan** [comment]
I've also been considering test-based guards, too:

```wew
guard Integer = Number where n => n % 1 == 0
```

**Comment by hedgehog1029** [comment]
I would suggest a `fn` or `def` prefix, to properly seperate function definitions.

**Comment by TheInitializer** [comment]
How will blocks be handled?

**Comment by hedgehog1029** [comment]
You could go with whitespace-sensitive (nicer to write) - the question is whether to use a do/end or do/whitespace syntax
```
def doSomething(value: String): String =>
    value.doThing()
end
```
or
```
def doSomething(value: String): String =>
    value.doThing()
# other code...
```
Given how if-blocks work I would suggest the latter.

**Comment by nanalan** [comment]
I'm thinking either do..end or {..} for blocks:

```wew
meme(adjective: String): String => {
  import log from system.console
  log(adjective .. ' meme!')
}

meme('Nice')
```

**Comment by nanalan** [comment]
@hedgehog1029 you misunderstand - if *blocksI* don't exist! `if..then..end`` is an expression and is not whitespace based.

**Comment by nanalan** [comment]
Continuing the `{..}` syntax, you should be able to use that anywhere:

```wew
let block = { ... }
if true then block else otherBlock
```

**Comment by hedgehog1029** [comment]
Yeah, I noticed after that if-blocks are not whitespace-sensitive. Do/end blocks are probably the best choice here.

**Comment by nanalan** [comment]
Looks like we've got function _definition_ syntax down:

```wew
let add = x => x + 1 # assign anonymous function to variable
minus(x) => x - 1 # named function
square(n: Number): Number => n ^ 2 # type guards
```

**Comment by nanalan** [comment]
We don't have block syntax covered yet, though.

Two options so far:
* `{ block }` <- I prefer this one
* `do block end`
